language: java
deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    tags: true
after_success:
  - mvn clean cobertura:cobertura coveralls:report